import type { SiteContent } from "./id";

// English dictionary — must match the shape of content/id.ts exactly.

export const enContent: SiteContent = {
  locale: "en",
  nav: {
    links: [
      { label: "Home", href: "#top" },
      { label: "About", href: "#about" },
      { label: "Experience", href: "#experience" },
      { label: "Projects", href: "#projects" },
      { label: "Skills", href: "#skills" },
      { label: "Contact", href: "#contact" },
    ],
    homeAria: "Risyad Ridwansyah — back to top",
    menuOpen: "Open navigation menu",
    menuClose: "Close navigation menu",
    languageLabel: "Choose language",
  },
  hero: {
    status: "Available for full-time roles",
    greeting: "hello, i'm",
    firstName: "Risyad",
    lastName: "Ridwansyah",
    roles: [
      "Web Developer",
      "Quality Assurance",
      "Backend Developer",
      "Fullstack Developer",
    ],
    tagline:
      "D3 Informatics Engineering graduate focused on modern web development, scalable backends, and software quality assurance (QA) — writing clean, tested, production-ready code.",
    ctaProjects: "View Projects",
    ctaCV: "Download CV",
    cvFileName: "CV-Risyad-Ridwansyah.pdf",
    scrollAria: "Scroll to projects section",
    socialGithub: "Risyad Ridwansyah's GitHub",
    socialLinkedin: "Risyad Ridwansyah's LinkedIn",
    socialEmail: "Email Risyad Ridwansyah",
    sectionAria: "Introduction to Risyad Ridwansyah",
  },
  stats: {
    sectionAria: "Key statistics",
    items: [
      { value: 3, suffix: "+", decimals: 0, label: "Industry Internships" },
      { value: 2, suffix: "", decimals: 0, label: "Projects & Service" },
      { value: 9, suffix: "", decimals: 0, label: "Technology Stack" },
      { value: 6, suffix: "+", decimals: 0, label: "Projects Delivered" },
    ],
  },
  about: {
    slug: "// about",
    num: "01",
    label: "About Me",
    title: "About",
    accent: "Me",
    description:
      "D3 Informatics Engineering graduate with industry internship experience in software development and testing.",
    ledePre: "I turn operational needs into ",
    ledeEm1: "stable systems",
    ledeMid: " that are ",
    ledeEm2: "ready for handover",
    ledePost: ".",
    paragraphs: [
      "I have hands-on experience in real operational environments as a Fullstack Developer at the Museum Geologi Bandung, building a collection management system integrated with single sign-on services and ministerial REST APIs. Previously I also developed operational web applications for meeting management and research mapping at the Center for Marine Geological Survey and Mapping.",
      "On the software quality side, I worked as a Software Quality Assurance at PT Primalogic Global Teknologi for a pension fund system — managing defect tracking and the bug life cycle, executing integration and black-box testing, and shepherding 102 reported bugs to an 84% resolution rate with the system stable and ready for handover.",
    ],
    highlights: [
      {
        value: "3+",
        label: "Industry Internships",
        detail: "Fullstack, SQA, Web Developer",
      },
      {
        value: "9",
        label: "Technology Stack",
        detail: "Web, QA, and backend",
      },
      {
        value: "6+",
        label: "Total Projects",
        detail: "Web, QA, and backend",
      },
      {
        value: "2",
        label: "Projects & Service",
        detail: "FocusTalk & PKM bootcamp speaker",
      },
    ],
    focusPre: "My focus:",
    focusText:
      "code quality, tested systems, and accountable work — from development through handover.",
    ctaCV: "Download CV",
    ctaContact: "Contact Me",
    pageExperience: "View Experience",
    pageProjects: "View Projects",
    portraitAlt: "Photo of Risyad Ridwansyah",
    sectionAria: "About Risyad Ridwansyah",
  },
  experience: {
    slug: "// experience",
    num: "02",
    label: "Experience",
    title: "Work",
    accent: "Experience",
    sub: "Three industry internships — software quality assurance, fullstack development, and web development.",
    endNote: "three roles, one standard:",
    endAccent: "production-ready",
    pageProjects: "View Projects",
    pageContact: "Work Together",
    items: [
      {
        role: "Software Quality Assurance Intern",
        company: "PT Primalogic Global Teknologi",
        initials: "PG",
        period: "Mar 2026 – Jun 2026",
        description:
          "Tested the Administrator, Accounting, and Membership modules of PT Pupuk Kaltim's Pension Fund system using Black-box Testing and Vendor Integration Testing (VIT). Focused on Defect Tracking and Bug Life Cycle flows, collaborating with the backend team to identify and resolve 102 bugs (84% resolution rate) and cut critical errors before client handover.",
        mainTech: [
          "Black-box Testing",
          "Vendor Integration Testing",
          "Defect Tracking",
          "Bug Life Cycle",
        ],
      },
      {
        role: "Fullstack Developer Intern",
        company: "Museum Geologi Bandung",
        initials: "MG",
        period: "Jun 2024 – Dec 2024",
        description:
          "Designed the KaGeo collection management system to transform the museum's manual record-keeping into a centralized digital platform. Integrated with the Ministry of ESDM REST API and CAS Single Sign-On (SSO), followed by backend optimization through a successful production deployment.",
        mainTech: [
          "Laravel",
          "React.js",
          "Tailwind CSS",
          "PostgreSQL",
          "REST API",
          "CAS SSO",
        ],
      },
      {
        role: "Web Developer Intern",
        company: "Center for Marine Geological Survey & Mapping",
        initials: "BB",
        period: "Jun 2022 – Sep 2022",
        description:
          "Supported internal digitalization by developing two operational web applications for meeting management and research map access, with structured database design to keep server-side reliable and optimize staff workflows.",
        mainTech: ["Laravel", "Bootstrap", "MySQL"],
      },
    ],
  },
  projects: {
    slug: "// projects",
    num: "03",
    label: "Selected Work",
    title: "Selected",
    accent: "Projects",
    sub: "A cross-section of platforms — from solo projects to applications used in real operations.",
    githubProfile: "https://github.com/rdwnsyh?tab=repositories",
    viewAll: "See all on GitHub",
    cardDetails: "details",
    cardAria: "View details for",
    modalRole: "Role",
    modalDemo: "Live Demo",
    modalRepo: "GitHub Repo",
    modalClose: "Close project details",
    modalDismiss: "Close",
    pageContact: "Work Together",
    pageSkills: "Explore Skills",
    items: [
      {
        title: "Client Project Progress Tracker",
        year: "2026",
        short:
          "Full-stack project management system for real-time client project tracking — milestone transparency and managerial reporting.",
        description:
          "The problem: client project progress was hard to monitor transparently and managerial reports were assembled manually. The solution: a full-stack platform with milestone transparency, automatic progress calculation, and professional managerial reporting — complete with a programmer role that uploads a report per progress entry and a comment thread per work item.",
        role: "Full-stack Developer",
        tech: ["C#", ".NET", "JavaScript", "HTML/CSS"],
        github: "https://github.com/rdwnsyh/client-project-progress-tracker",
        demo: null,
        icon: "dashboard",
        image: "/images/halaman dashboard EVM 1.png",
      },
      {
        title: "KaGeo — Museum Collection System",
        year: "2024",
        short:
          "Centralized digital platform replacing manual museum collection records — integrated with SSO & ministerial REST APIs.",
        description:
          "Built as a Fullstack Developer Intern at Museum Geologi Bandung: transforming manual record-keeping into a centralized digital platform with CAS Single Sign-On, Ministry of ESDM REST APIs, backend optimization, and a production deployment.",
        role: "Fullstack Developer Intern",
        tech: ["Laravel", "React.js", "PostgreSQL", "REST API"],
        github: "https://github.com/rdwnsyh/app_museum_geologi",
        demo: null,
        icon: "landmark",
        image: "/images/Kageo.PNG",
      },
      {
        title: "FocusTalk — Smart Intervention System",
        year: "2025",
        short:
          "Educational mobile app that counters study distractions via system overlay — powered by a heuristic rule-based API.",
        description:
          "Final-year project: design and development of a smart-intervention and user activity control system based on a Heuristic Rule-Based algorithm for English learning. The mobile app (Flutter) detects distractions through a system overlay window, powered by a backend API (FastAPI) as the intervention rule engine.",
        role: "Mobile & Backend Developer",
        tech: ["Flutter", "FastAPI", "Python", "Heuristic Rule-Based"],
        github: "https://github.com/rdwnsyh/focustalk_app",
        demo: null,
        icon: "smartphone",
        image: "/images/focustalk.jpg",
        related: [
          {
            label: "Backend API",
            href: "https://github.com/rdwnsyh/be_api_focustalk",
          },
        ],
      },
      {
        title: "Cakrawala Muda Indonesia",
        year: "2025",
        short:
          "Student competition information portal — landing page and event catalog.",
        description:
          "Student competition information website: a public landing page plus managed competition content so events are easy to discover and join.",
        role: "Web Developer",
        tech: ["Laravel", "PHP", "Blade"],
        github: "https://github.com/rdwnsyh/cakrawala_muda_indonesia",
        demo: null,
        icon: "trophy",
        image: "/images/cakrawala_muda_indonesia.png",
      },
      {
        title: "Berkah Expedisi",
        year: "2025",
        short:
          "Company profile and information system for an expedition service.",
        description:
          "Company profile and information system for Berkah Expedisi: service profile, operational information, and company content management.",
        role: "Web Developer",
        tech: ["Laravel", "PHP", "Blade", "CSS"],
        github: "https://github.com/rdwnsyh/berkah-expedisi",
        demo: null,
        icon: "truck",
        image: "/images/berkah_expedisi.png",
      },
      {
        title: "BBSPGL — Operational & Research Mapping Web Applications",
        year: "2022",
        short:
          "Two operational web applications utilizing Laravel & Bootstrap to streamline meeting management and internal research map accessibility.",
        description:
          "Developed during internship as Web Developer at Center for Marine Geological Survey and Mapping (BBSPGL), Bandung. Built two operational, responsive web applications utilizing Laravel and Bootstrap to streamline meeting management and improve research map accessibility for internal users. Designed and implemented structured MySQL databases to ensure organized data storage and reliable querying, managed stable server-side operations by maintaining backend reliability and enforcing security measures, and facilitated organizational digitization efforts.",
        role: "Web Developer Intern",
        tech: ["Laravel", "Bootstrap", "MySQL", "PHP"],
        github: "https://github.com/rdwnsyh",
        demo: null,
        icon: "compass",
        image: "/images/bbspgl.PNG",
      },
    ],
  },
  skills: {
    slug: "// skills",
    num: "04",
    label: "Skills",
    title: "Technical",
    accent: "Skills",
    tagline: "The tools I use to build, integrate, and test software.",
    pageContact: "Contact Me",
    pageProjects: "View Projects",
    categories: [
      {
        key: "languages",
        title: "Languages",
        icon: "code",
        items: [
          { name: "PHP", abbr: "PHP" },
          { name: "JavaScript", abbr: "JS" },
          { name: "TypeScript", abbr: "TS" },
          { name: "Python", abbr: "Py" },
          { name: "Dart", abbr: "Da" },
          { name: "C#", abbr: "C#" },
          { name: "HTML", abbr: "H5" },
          { name: "CSS", abbr: "C3" },
        ],
      },
      {
        key: "frameworks",
        title: "Frameworks & Libraries",
        icon: "layers",
        items: [
          { name: "Laravel", abbr: "La" },
          { name: "React.js", abbr: "Re" },
          { name: "Next.js", abbr: "Nx" },
          { name: "Flutter", abbr: "Fl" },
          { name: "FastAPI", abbr: "FA" },
          { name: ".NET", abbr: ".N" },
          { name: "Tailwind CSS", abbr: "Tw" },
          { name: "Bootstrap", abbr: "Bs" },
        ],
      },
      {
        key: "tools",
        title: "Tools & Databases",
        icon: "database",
        items: [
          { name: "PostgreSQL", abbr: "Pg" },
          { name: "MySQL", abbr: "My" },
          { name: "MongoDB", abbr: "Mo" },
          { name: "Git & GitHub", abbr: "Gt" },
          { name: "Vercel", abbr: "Ve" },
        ],
      },
      {
        key: "qa",
        title: "QA & Methodologies",
        icon: "shield",
        items: [
          { name: "Black-box Testing", abbr: "Bb" },
          { name: "Integration Testing", abbr: "IT" },
          { name: "VIT", abbr: "VI" },
          { name: "Defect Tracking", abbr: "Dt" },
          { name: "Bug Life Cycle", abbr: "Bl" },
        ],
      },
    ],
  },
  contact: {
    slug: "// contact",
    num: "05",
    label: "Contact",
    title: "Get in",
    accent: "Touch",
    tagline:
      "Have a project, a full-time role, or just want to talk? Your message lands straight in my inbox.",
    introTitle: "Let's connect",
    introDescription:
      "Open to full-time Software Engineer / Web Developer roles and project collaboration. I usually reply within 1–2 business days.",
    location: "Bandung, Indonesia",
    emailLabel: "Email",
    linkedinLabel: "LinkedIn",
    githubLabel: "GitHub",
    contactVia: "Contact me via",
    formName: "Name",
    formNamePlaceholder: "Your name",
    formEmail: "Email",
    formEmailPlaceholder: "name@email.com",
    formMessage: "Message",
    formMessagePlaceholder: "Tell me about the project or role…",
    formSubmit: "Send Message",
    formNote:
      "No backend — this button opens your email app with the message pre-filled.",
    mailSubject: "Portfolio message from",
    successTitle: "Message ready to send!",
    successTextPre:
      "Your email app should have opened with the message filled in. If not, reach me directly at",
    successAgain: "Send Another",
  },
  footer: {
    ctaEyebrow: "have a project in mind?",
    ctaTitle: "Let's build something",
    ctaAccent: "great",
    ctaAria: "Contact Risyad by email about a project",
    tagline:
      "Software engineer crafting modern web experiences — clean, tested, and production-ready.",
    navHeading: "Navigate",
    connectHeading: "Connect",
    logoAria: "Risyad Ridwansyah — back to top",
    builtWith: "Built with Next.js & Tailwind CSS",
  },
  shared: {
    name: "Risyad Ridwansyah",
    github: "https://github.com/rdwnsyh",
    linkedin: "https://www.linkedin.com/in/risyad-ridwansyah/",
    email: "risyadridwansyah@gmail.com",
    cvPath: "/CV-Risyad-Ridwansyah.pdf",
    projectsAnchor: "#projects",
  },
  theme: {
    toggle: "Toggle theme",
    dark: "Dark mode",
    light: "Light mode",
  },
};
