// Kamus Bahasa Indonesia — sumber kebenaran seluruh teks situs.
// Pasangannya: content/en.ts (wajib bentuknya sama persis).

export const idContent = {
  locale: "id" as "id" | "en",
  nav: {
    links: [
      { label: "Beranda", href: "#top" },
      { label: "Tentang", href: "#about" },
      { label: "Pengalaman", href: "#experience" },
      { label: "Proyek", href: "#projects" },
      { label: "Keahlian", href: "#skills" },
      { label: "Kontak", href: "#contact" },
    ],
    homeAria: "Risyad Ridwansyah — kembali ke atas",
    menuOpen: "Buka menu navigasi",
    menuClose: "Tutup menu navigasi",
    languageLabel: "Pilih bahasa",
  },
  hero: {
    status: "Tersedia untuk full-time",
    greeting: "halo, saya",
    firstName: "Risyad",
    lastName: "Ridwansyah",
    roles: [
      "Web Developer",
      "Quality Assurance",
      "Backend Developer",
      "Fullstack Developer",
    ],
    tagline:
      "Lulusan D3 Teknik Informatika yang berfokus pada pengembangan web modern, backend yang scalable, hingga pengujian kualitas perangkat lunak (QA) — menulis kode yang bersih, teruji, dan siap produksi.",
    ctaProjects: "Lihat Proyek",
    ctaCV: "Unduh CV",
    cvFileName: "CV-Risyad-Ridwansyah.pdf",
    scrollAria: "Gulir ke bagian proyek",
    socialGithub: "GitHub Risyad Ridwansyah",
    socialLinkedin: "LinkedIn Risyad Ridwansyah",
    socialEmail: "Email Risyad Ridwansyah",
    sectionAria: "Perkenalan Risyad Ridwansyah",
  },
  stats: {
    sectionAria: "Statistik utama",
    items: [
      { value: 3, suffix: "+", decimals: 0, label: "Magang Industri" },
      { value: 102, suffix: "", decimals: 0, label: "Bug Ditangani (SQA)" },
      { value: 84, suffix: "%", decimals: 0, label: "Resolusi Bug" },
      { value: 3.78, suffix: "", decimals: 2, label: "IPK D3 Informatika" },
    ],
  },
  about: {
    slug: "// tentang",
    num: "01",
    label: "Tentang Saya",
    title: "Tentang",
    accent: "Saya",
    description:
      "Lulusan D3 Teknik Informatika dengan pengalaman magang industri di pengembangan dan pengujian perangkat lunak.",
    ledePre: "Saya mengubah kebutuhan operasional menjadi ",
    ledeEm1: "sistem yang stabil",
    ledeMid: " dan ",
    ledeEm2: "siap serah terima",
    ledePost: ".",
    paragraphs: [
      "Saya berpengalaman bekerja di lingkungan operasional nyata sebagai Fullstack Developer di Museum Geologi Bandung, membangun sistem manajemen koleksi yang terintegrasi dengan layanan single sign-on dan REST API kementerian. Sebelumnya saya juga mengembangkan aplikasi web operasional untuk manajemen rapat dan pemetaan riset di Balai Besar Survei dan Pemetaan Geologi Kelautan.",
      "Di sisi kualitas perangkat lunak, saya berpengalaman sebagai Software Quality Assurance di PT Primalogic Global Teknologi untuk sistem dana pensiun — mengelola defect tracking dan bug life cycle, mengeksekusi integration testing dan black-box testing, serta mengawal 102 temuan bug hingga 84% terselesaikan dan sistem stabil siap serah terima.",
    ],
    highlights: [
      {
        value: "3+",
        label: "Magang Industri",
        detail: "Fullstack, SQA, Web Developer",
      },
      {
        value: "84%",
        label: "Bug Resolution Rate",
        detail: "102 bug dikawal hingga siap serah terima",
      },
      {
        value: "3.78",
        label: "IPK / 4.00",
        detail: "D3 Teknik Informatika",
      },
      {
        value: "2",
        label: "Proyek & Pengabdian",
        detail: "FocusTalk & pemateri bootcamp PKM",
      },
    ],
    focusPre: "Fokus saya:",
    focusText:
      "kualitas kode, sistem yang teruji, dan hasil kerja yang bisa dipertanggungjawabkan — dari pengembangan hingga serah terima.",
    ctaCV: "Unduh CV",
    ctaContact: "Hubungi Saya",
    pageExperience: "Lihat Pengalaman",
    pageProjects: "Lihat Proyek",
    portraitAlt: "Foto Risyad Ridwansyah",
    sectionAria: "Tentang Risyad Ridwansyah",
  },
  experience: {
    slug: "// pengalaman",
    num: "02",
    label: "Pengalaman",
    title: "Pengalaman",
    accent: "Kerja",
    sub: "Tiga magang industri — software quality assurance, fullstack development, dan web development.",
    endNote: "tiga pengalaman, satu standar:",
    endAccent: "siap produksi",
    pageProjects: "Lihat Proyek",
    pageContact: "Ajak Kerja Sama",
    items: [
      {
        role: "Software Quality Assurance Intern",
        company: "PT Primalogic Global Teknologi",
        initials: "PG",
        period: "Mar 2026 – Jun 2026",
        description:
          "Menguji modul Administrator, Akuntansi, dan Keanggotaan sistem Dana Pensiun PT Pupuk Kaltim dengan Black-box Testing dan Vendor Integration Testing (VIT). Berfokus pada alur Defect Tracking dan Bug Life Cycle, kolaborasi bersama tim backend mengidentifikasi serta menyelesaikan 102 bug (resolution rate 84%) dan menekan eror kritis sebelum handover ke klien.",
        mainTech: [
          "Black-box Testing",
          "Vendor Integration Testing",
          "Defect Tracking",
          "Bug Life Cycle",
        ],
      },
      {
        role: "Fullstack Developer Intern",
        company: "Museum Geologi Bandung",
        initials: "MG",
        period: "Jun 2024 – Des 2024",
        description:
          "Merancang sistem manajemen koleksi KaGeo untuk mentransformasi pencatatan manual museum menjadi platform digital tersentralisasi. Terintegrasi dengan REST API Kementerian ESDM serta CAS Single Sign-On (SSO), dilanjutkan optimasi backend hingga berhasil deploy ke production.",
        mainTech: [
          "Laravel",
          "React.js",
          "Tailwind CSS",
          "PostgreSQL",
          "REST API",
          "CAS SSO",
        ],
      },
      {
        role: "Web Developer Intern",
        company: "Balai Besar Survei & Pemetaan Geologi Kelautan",
        initials: "BB",
        period: "Jun 2022 – Sep 2022",
        description:
          "Mendukung digitalisasi internal dengan mengembangkan dua aplikasi web operasional untuk manajemen rapat dan akses peta riset, dengan perancangan basis data terstruktur untuk menjaga keandalan server-side dan mengoptimalkan alur kerja staf.",
        mainTech: ["Laravel", "Bootstrap", "MySQL"],
      },
    ],
  },
  projects: {
    slug: "// proyek",
    num: "03",
    label: "Proyek Pilihan",
    title: "Proyek",
    accent: "Pilihan",
    sub: "Potongan lintas platform — dari proyek mandiri hingga aplikasi yang dipakai operasional sungguhan.",
    githubProfile: "https://github.com/rdwnsyh?tab=repositories",
    viewAll: "Lihat semua di GitHub",
    cardDetails: "detail",
    cardAria: "Lihat detail",
    modalRole: "Peran",
    modalDemo: "Live Demo",
    modalRepo: "GitHub Repo",
    modalClose: "Tutup detail proyek",
    modalDismiss: "Tutup",
    pageContact: "Ajak Kerja Sama",
    pageSkills: "Jelajahi Skills",
    items: [
      {
        title: "Client Project Progress Tracker",
        year: "2026",
        short:
          "Sistem manajemen proyek full-stack untuk memantau progres proyek klien real-time — transparansi milestone dan pelaporan manajerial.",
        description:
          "Masalah yang dijawab: progres proyek klien sulit dipantau transparan dan laporan manajerial tersusun manual. Solusinya: platform full-stack dengan transparansi milestone, perhitungan progres otomatis, dan pelaporan manajerial profesional — lengkap dengan peran programmer yang mengunggah laporan tiap progres serta kolom komentar per work item.",
        role: "Full-stack Developer",
        tech: ["C#", ".NET", "JavaScript", "HTML/CSS"],
        github: "https://github.com/rdwnsyh/client-project-progress-tracker",
        demo: null,
        icon: "dashboard",
        image: "/images/halaman dashboard EVM 1.png",
      },
      {
        title: "KaGeo — Sistem Koleksi Museum Geologi",
        year: "2024",
        short:
          "Platform digital tersentralisasi pengganti pencatatan manual koleksi museum — terintegrasi SSO & REST API kementerian.",
        description:
          "Dibangun saat magang sebagai Fullstack Developer Intern di Museum Geologi Bandung: mentransformasi pencatatan manual menjadi platform digital tersentralisasi dengan CAS Single Sign-On, REST API Kementerian ESDM, optimasi backend, hingga deploy ke production.",
        role: "Fullstack Developer Intern",
        tech: ["Laravel", "React.js", "PostgreSQL", "REST API"],
        github: "https://github.com/rdwnsyh/app_museum_geologi",
        demo: null,
        icon: "landmark",
        image: "/images/Kageo.PNG",
      },
      {
        title: "FocusTalk — Smart Intervention System",
        year: "2025",
        short:
          "Aplikasi mobile edukasi penangkal distraksi belajar via system overlay — didukung API heuristic rule-based.",
        description:
          "Proyek tugas akhir: rancang bangun sistem smart-intervention dan kontrol aktivitas pengguna berbasis algoritma Heuristic Rule-Based untuk pembelajaran bahasa Inggris. Aplikasi mobile (Flutter) mendeteksi distraksi lewat system overlay window, ditenagai API backend (FastAPI) sebagai mesin aturan intervensi.",
        role: "Mobile & Backend Developer",
        tech: ["Flutter", "FastAPI", "Python", "Heuristic Rule-Based"],
        github: "https://github.com/rdwnsyh/focustalk_app",
        demo: null,
        icon: "smartphone",
        image: "/images/focustalk.jpg",
        related: [
          {
            label: "Backend API",
            href: "https://github.com/rdwnsyh/be_api_focustalk",
          },
        ],
      },
      {
        title: "Cakrawala Muda Indonesia",
        year: "2025",
        short: "Web informasi kompetisi mahasiswa — landing page dan katalog lomba.",
        description:
          "Website informasi kompetisi mahasiswa: landing page publik plus pengelolaan konten informasi lomba agar mudah ditemukan dan diikuti.",
        role: "Web Developer",
        tech: ["Laravel", "PHP", "Blade"],
        github: "https://github.com/rdwnsyh/cakrawala_muda_indonesia",
        demo: null,
        icon: "trophy",
        image: "/images/cakrawala_muda_indonesia.png",
      },
      {
        title: "Berkah Expedisi",
        year: "2025",
        short: "Company profile dan sistem informasi jasa ekspedisi.",
        description:
          "Company profile sekaligus sistem informasi Berkah Expedisi: profil layanan, informasi operasional, dan pengelolaan konten perusahaan.",
        role: "Web Developer",
        tech: ["Laravel", "PHP", "Blade", "CSS"],
        github: "https://github.com/rdwnsyh/berkah-expedisi",
        demo: null,
        icon: "truck",
        image: "/images/berkah_expedisi.png",
      },
      {
        title: "BBSPGL — Aplikasi Web Operasional & Pemetaan Riset",
        year: "2022",
        short:
          "Dua aplikasi web operasional berbasis Laravel & Bootstrap untuk manajemen rapat dan aksesibilitas peta riset geologi kelautan.",
        description:
          "Dikembangkan saat magang sebagai Web Developer di Balai Besar Survei dan Pemetaan Geologi Kelautan (BBSPGL), Bandung: membangun dua aplikasi web operasional dan responsif berbasis Laravel dan Bootstrap untuk menyederhanakan manajemen rapat serta meningkatkan aksesibilitas peta riset bagi pengguna internal. Merancang basis data MySQL terstruktur untuk penyimpanan terorganisasi dan query yang andal, mengelola stabilitas operasional server-side dengan standar keamanan data, serta memfasilitasi alur digitalisasi organisasi.",
        role: "Web Developer Intern",
        tech: ["Laravel", "Bootstrap", "MySQL", "PHP"],
        github: "https://github.com/rdwnsyh",
        demo: null,
        icon: "compass",
        image: "/images/bbspgl.PNG",
      },
    ],
  },
  skills: {
    slug: "// keahlian",
    num: "04",
    label: "Keahlian",
    title: "Technical",
    accent: "Skills",
    tagline:
      "Perangkat yang saya pakai untuk membangun, mengintegrasikan, dan menguji perangkat lunak.",
    pageContact: "Hubungi Saya",
    pageProjects: "Lihat Proyek",
    categories: [
      {
        key: "languages",
        title: "Languages",
        icon: "code",
        items: [
          { name: "PHP", abbr: "PHP" },
          { name: "JavaScript", abbr: "JS" },
          { name: "TypeScript", abbr: "TS" },
          { name: "Python", abbr: "Py" },
          { name: "Dart", abbr: "Da" },
          { name: "C#", abbr: "C#" },
          { name: "HTML", abbr: "H5" },
          { name: "CSS", abbr: "C3" },
        ],
      },
      {
        key: "frameworks",
        title: "Frameworks & Libraries",
        icon: "layers",
        items: [
          { name: "Laravel", abbr: "La" },
          { name: "React.js", abbr: "Re" },
          { name: "Next.js", abbr: "Nx" },
          { name: "Flutter", abbr: "Fl" },
          { name: "FastAPI", abbr: "FA" },
          { name: ".NET", abbr: ".N" },
          { name: "Tailwind CSS", abbr: "Tw" },
          { name: "Bootstrap", abbr: "Bs" },
        ],
      },
      {
        key: "tools",
        title: "Tools & Databases",
        icon: "database",
        items: [
          { name: "PostgreSQL", abbr: "Pg" },
          { name: "MySQL", abbr: "My" },
          { name: "MongoDB", abbr: "Mo" },
          { name: "Git & GitHub", abbr: "Gt" },
          { name: "Vercel", abbr: "Ve" },
        ],
      },
      {
        key: "qa",
        title: "QA & Methodologies",
        icon: "shield",
        items: [
          { name: "Black-box Testing", abbr: "Bb" },
          { name: "Integration Testing", abbr: "IT" },
          { name: "VIT", abbr: "VI" },
          { name: "Defect Tracking", abbr: "Dt" },
          { name: "Bug Life Cycle", abbr: "Bl" },
        ],
      },
    ],
  },
  contact: {
    slug: "// kontak",
    num: "05",
    label: "Kontak",
    title: "Hubungi",
    accent: "Saya",
    tagline:
      "Punya proyek, peran full-time, atau sekadar ingin berdiskusi? Pesanmu langsung masuk ke email saya.",
    introTitle: "Mari terhubung",
    introDescription:
      "Terbuka untuk peran full-time Software Engineer / Web Developer serta kolaborasi proyek. Rata-rata saya membalas dalam 1–2 hari kerja.",
    location: "Bandung, Indonesia",
    emailLabel: "Email",
    linkedinLabel: "LinkedIn",
    githubLabel: "GitHub",
    contactVia: "Hubungi via",
    formName: "Nama",
    formNamePlaceholder: "Nama kamu",
    formEmail: "Email",
    formEmailPlaceholder: "nama@email.com",
    formMessage: "Pesan",
    formMessagePlaceholder: "Ceritakan proyek atau peran yang ditawarkan…",
    formSubmit: "Kirim Pesan",
    formNote: "Tanpa backend — tombol ini membuka aplikasi email dengan pesanmu sudah terisi rapi.",
    mailSubject: "Pesan portofolio dari",
    successTitle: "Pesan siap dikirim!",
    successTextPre:
      "Aplikasi email-mu seharusnya sudah terbuka dengan pesan terisi. Jika tidak, hubungi langsung ke",
    successAgain: "Kirim Lagi",
  },
  footer: {
    ctaEyebrow: "ada proyek dalam pikiran?",
    ctaTitle: "Mari bangun sesuatu",
    ctaAccent: "yang hebat",
    ctaAria: "Hubungi Risyad via email untuk proyek",
    tagline:
      "Software Engineer yang merancang pengalaman web modern — bersih, teruji, dan siap produksi.",
    navHeading: "Navigasi",
    connectHeading: "Terhubung",
    logoAria: "Risyad Ridwansyah — kembali ke atas",
    builtWith: "Dibangun dengan Next.js & Tailwind CSS",
  },
  shared: {
    name: "Risyad Ridwansyah",
    github: "https://github.com/rdwnsyh",
    linkedin: "https://www.linkedin.com/in/risyad-ridwansyah/",
    email: "risyadridwansyah@gmail.com",
    cvPath: "/CV-Risyad-Ridwansyah.pdf",
    projectsAnchor: "#projects",
  },
  theme: {
    toggle: "Ganti tema",
    dark: "Mode gelap",
    light: "Mode terang",
  },
};

export type SiteContent = typeof idContent;
